supporting_materials:
  system_prompt: "system_prompt.txt"
  prompt_template: "prompt_template.txt"

input:
  folder_path: "../markdown_files/" # Path to the markdown files

variables:
  "{content}": "markdown_content" # Reads full markdown file
  "{frontmatter}": "yaml_frontmatter" # Reads YAML frontmatter
