supporting_materials:
  system_prompt: "system_prompt.txt"
  prompt_template: "prompt_template.txt"

variables:
  "{content}": "markdown_content" # Reads full markdown file
  "{frontmatter}": "yaml_frontmatter" # Reads YAML frontmatter
