execution:
  batch_processing: true
  incremental_saving: true
  max_retries: 3

supporting_materials:
  system_prompt: "system_prompt.txt"
  prompt_template: "prompt_template.txt"
  additional_inclusions:
    ontology: "ontology.yaml"

variables:
  "{title}": "title"
  "{description}": "description"
